name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v2

      - name: Set up the Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build the container image
        run: |
          sh ./push-docker-image.sh

      - name: Authenticate to Google Cloud
        run: gcloud auth configure-docker

      - name: Terraform versioning
        run: |
          sh ./terraform-version.sh

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dev-service \
            --image gcr.io/$GCP_PROJECT_ID/umar-demo-service \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated

      - name: Deploy to GCS
        run: |
          gsutil cp -r ./public gs://umar-demo-service
